POST http://localhost:3002/register
Content-Type: application/json

{
    "email": "oooo",
    "password": "oooo"
}

###

POST http://localhost:3002/login
Content-Type: application/json

{
    "email": "oooo",
    "password": "oooo"
}

###

DELETE http://localhost:3033/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpbW9uIiwiaWF0IjoxNjU0MTA4MDEwfQ.C8RjTLoK2u-YuYriEjFEv7CuzMsF3WaS1NGZt2jDo2I"
}

###

# {
#   "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJvb29vIiwicGFzc3dvcmQiOiIkMmIkMTAkamowdFEwWUp0UVRJVUUzLmRDTVU3LnMzUjVTajlnVmVyU1prNjYwWkNMTUJMQlJRVkRRZUciLCJyZWZyZXNoX3Rva2VuIjpudWxsLCJzdGF0dXMiOiJ7XCJyb2xlc1wiOiBbe1wibmFtZVwiOiBcIlNUVURFTlRcIn1dLCBcImJhZGdlc1wiOiBbXX0iLCJpYXQiOjE2NTU5MTE2MTgsImV4cCI6MTY1NTkxMjIxOH0.CZijMjPi5OpOt8X_lfRFaQ0ix9vsbMrrV8lCS6PRjck",
#   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJvb29vIiwicGFzc3dvcmQiOiIkMmIkMTAkamowdFEwWUp0UVRJVUUzLmRDTVU3LnMzUjVTajlnVmVyU1prNjYwWkNMTUJMQlJRVkRRZUciLCJyZWZyZXNoX3Rva2VuIjpudWxsLCJzdGF0dXMiOiJ7XCJyb2xlc1wiOiBbe1wibmFtZVwiOiBcIlNUVURFTlRcIn1dLCBcImJhZGdlc1wiOiBbXX0iLCJpYXQiOjE2NTU5MTE2MTh9.onfZCTNFoNWhbMtPm2oUOdzcef5IdEtZluJdQARbMh0",
#   "auth": true,
#   "user": {
#     "id": 5,
#     "email": "oooo",
#     "password": "$2b$10$jj0tQ0YJtQTIUE3.dCMU7.s3R5Sj9gVerSZk660ZCLMBLBRQVDQeG",
#     "refresh_token": null,
#     "status": "{\"roles\": [{\"name\": \"STUDENT\"}], \"badges\": []}"
#   }
# }


POST http://localhost:3002/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJzaW1vbmFzLnphYnVsaW9uaXNAaWNsb3VkLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJC40dFYzMXZGajJHQW9NT0luRkF1SE9qaWJUQ09ML0ozQU1uaEtmdXZOMnFWaS9PejhIRmhXIiwic3RhdHVzIjoie1wicm9sZXNcIjogW3tcIm5hbWVcIjogXCJTVFVERU5UXCJ9XSwgXCJiYWRnZXNcIjogW119IiwicmVmcmVzaF90b2tlbiI6bnVsbCwiaWF0IjoxNjU1OTI2MDkzfQ.AYDxnYSsKssQU97Z4y3DYUejSn3xuo2BfcOxpDxG-Ao"
}

###



POST http://localhost:3003/login
Content-Type: application/json

{
    "username": "pepe"
}

###

GET http://localhost:3003/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcGUiLCJpYXQiOjE2NTQxMDU1NTl9.lvO0KYVEd3MnpjiFwjpnN94DVasN310QcdVDvJUDRew

###

GET http://localhost:3000/api/ping